### ISSUE TITLE
I can't deploy to staging

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow-provisioning#174]
I'm following this guide trying to deploy timeoverflow/develop to staging https://github.com/coopdevs/timeoverflow/wiki/Deploy-to-staging

I already rebuild my lxc but I still having this error when execute `bundle exec cap staging deploy 
`
```
INFO [3280025d] Running sudo systemctl reload timeoverflow as timeoverflow@staging.timeoverflow.org
 DEBUG [3280025d] Command: sudo systemctl reload timeoverflow
 DEBUG [3280025d] 	timeoverflow.service is not active, cannot reload.
#<Thread:0x00005644785e5b88@/var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	8: from /var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `run'
	7: from /var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	6: from config/deploy.rb:54:in `block (3 levels) in <top (required)>'
	5: from /var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:80:in `execute'
	4: from /var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	3: from /var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `tap'
	2: from /var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	1: from /var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/command.rb:97:in `exit_status=': sudo systemctl reload timeoverflow exit status: 1 (SSHKit::Command::Failed)
sudo systemctl reload timeoverflow stdout: Nothing written
sudo systemctl reload timeoverflow stderr: timeoverflow.service is not active, cannot reload.
	1: from /var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/var/www/timeoverflow/vendor/bundle/ruby/2.6.0/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as timeoverflow@staging.timeoverflow.org: sudo systemctl reload timeoverflow exit status: 1 (SSHKit::Runner::ExecuteError)
sudo systemctl reload timeoverflow stdout: Nothing written
sudo systemctl reload timeoverflow stderr: timeoverflow.service is not active, cannot reload.
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as timeoverflow@staging.timeoverflow.org: sudo systemctl reload timeoverflow exit status: 1
sudo systemctl reload timeoverflow stdout: Nothing written
sudo systemctl reload timeoverflow stderr: timeoverflow.service is not active, cannot reload.
```

cc @danypr92

**Comment by enricostano** [comment]
@sseerrggii the guide says `restart`, but it seems that you executed `reload`. Could be?

**Comment by sseerrggii** [comment]
This error prompt in step 4. Deploy to staging
when I execute:

`bundle exec cap staging deploy `
